[package]
name = "circuits"
type = "bin"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v4.1.0-rc.2", directory = "aztec" }
uint_note = { path = "../uint-note" }
