
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import DaoVotingContractArtifactJson from '../target/dao_voting-DaoVoting.json' with { type: 'json' };
export const DaoVotingContractArtifact = loadContractArtifact(DaoVotingContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract DaoVoting;
 */
export class DaoVotingContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, DaoVotingContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): DaoVotingContract {
    return Contract.at(address, DaoVotingContract.artifact, wallet) as DaoVotingContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, eth_token_address: (bigint | number)[], eth_balance_slot: FieldLike, eth_chain_id: (bigint | number)) {
    return new DeployMethod<DaoVotingContract>(PublicKeys.default(), wallet, DaoVotingContractArtifact, (instance, wallet) => DaoVotingContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, eth_token_address: (bigint | number)[], eth_balance_slot: FieldLike, eth_chain_id: (bigint | number)) {
    return new DeployMethod<DaoVotingContract>(publicKeys, wallet, DaoVotingContractArtifact, (instance, wallet) => DaoVotingContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof DaoVotingContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<DaoVotingContract['methods'][M]>
  ) {
    return new DeployMethod<DaoVotingContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      DaoVotingContractArtifact,
      (instance, wallet) => DaoVotingContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return DaoVotingContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(DaoVotingContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'eth_token_address' | 'eth_balance_slot' | 'eth_chain_id' | 'next_proposal_id' | 'proposals' | 'vote_tallies'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
eth_token_address: {
      slot: new Fr(3n),
    },
eth_balance_slot: {
      slot: new Fr(24n),
    },
eth_chain_id: {
      slot: new Fr(26n),
    },
next_proposal_id: {
      slot: new Fr(28n),
    },
proposals: {
      slot: new Fr(29n),
    },
vote_tallies: {
      slot: new Fr(30n),
    }
      } as ContractStorageLayout<'admin' | 'eth_token_address' | 'eth_balance_slot' | 'eth_chain_id' | 'next_proposal_id' | 'proposals' | 'vote_tallies'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** cancel_proposal(proposal_id: field) */
    cancel_proposal: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cast_vote(proposal_id: field, choice: integer, eth_address: array, claimed_tier: integer) */
    cast_vote: ((proposal_id: FieldLike, choice: (bigint | number), eth_address: (bigint | number)[], claimed_tier: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct, eth_token_address: array, eth_balance_slot: field, eth_chain_id: integer) */
    constructor: ((admin: AztecAddressLike, eth_token_address: (bigint | number)[], eth_balance_slot: FieldLike, eth_chain_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_proposal(description_hash: field, snapshot_block: integer, voting_start: integer, voting_end: integer, num_choices: integer) */
    create_proposal: ((description_hash: FieldLike, snapshot_block: (bigint | number), voting_start: (bigint | number), voting_end: (bigint | number), num_choices: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_all_tiers() */
    get_all_tiers: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_eth_token_config() */
    get_eth_token_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_next_proposal_id() */
    get_next_proposal_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal(proposal_id: field) */
    get_proposal: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_results(proposal_id: field) */
    get_results: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_tier_info(tier: integer) */
    get_tier_info: ((tier: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_vote_count(proposal_id: field, choice: integer) */
    get_vote_count: ((proposal_id: FieldLike, choice: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
